# Generated by Django 3.0.8 on 2020-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emp_id',
            field=models.CharField(default='base12', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
